trigger:
  branches:
    include:
      - main

pr: none

pool:
  name: DESKTOP-T0DP320

steps:
- script: |
    git clone https://github.com/abdi2148/AKS-Web.git
    cd AKS-Web
    npm install
    npm test
  displayName: 'Test Frontend'

- script: |
    git clone https://github.com/abdi2148/AKS-API.git
    cd AKS-API
    npm install
    npm test
  displayName: 'Test Backend'