trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  name: Default

steps:
  - name: Checkout AKS-Web repository
    displayName: 'Checkout AKS-Web'
    steps:
      - checkout: self
        clean: true
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'
      - script: |
          cd AKS-Web
          npm ci
        displayName: 'Install dependencies and run tests for AKS-Web'

  - name: Checkout AKS-API repository
    displayName: 'Checkout AKS-API'
    steps:
      - checkout: self
        clean: true
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'
      - script: |
          cd AKS-API
          npm ci
          npm run test:mongodb
        displayName: 'Install dependencies and run tests for AKS-API with MongoDB'